### PR TITLE
Rewrite core

### PR DESCRIPTION
**Pull request by princemaple**
Hi @azizk ,

I've rebased your work into this branch. If you have further changes on your own branch I can pull them into this one as well. Let me know when everything is done.

Thanks heaps!

closes #11

### CODE REVIEW

**Comment by princemaple** [comment]
I've also sent you an invitation to be a collaborator on this repo. If you accept the invitation, when we are done with these changes, you can nuke your own fork (both on github and your local) and clone this repo directly and will be able to push your branches of this repo.

**Comment by princemaple** [comment]
@azizk FYI I don't intend to keep ST3 updated.

**Comment by princemaple** [comment]
**If** extra work was required ^

**Comment by princemaple** [comment]
Is this one ready now?

**Comment by azizk** [comment]
@princemaple Yeah, no problem. I'd like to try and keep things compatible for now. It's not difficult. But is it a hassle to create an extra legacy package for ST3? I'm sure some users would benefit from it.

Status update: I thought I'm getting closer to the end but it seems that I keep uncovering issues every time I'm writing tests. At least it's very thorough now and I managed to fix the automatic CI tests. I'll be finished when I have all the necessary test cases and then I'll give it a final clean-up.

**Comment by princemaple** [comment]
Thanks, let me know when you feel comfortable to have this one go in.



> But is it a hassle to create an extra legacy package for ST3? I'm sure some users would benefit from it.

I just opened this PR https://github.com/wbond/package_control_channel/pull/8105 so we can have legacy support for ST3.

My other package for Angular HTML  is also using this strategy.
https://github.com/princemaple/ngx-html-syntax
https://github.com/wbond/package_control_channel/blob/master/repository/n.json#L536-L551

**Comment by princemaple** [comment]
Is this stable enough for a release now?

**Comment by azizk** [comment]
Hi! It's pretty stable now. But there's a bug I found yesterday. Going to commit the fix today. As a last thing I want to go over the `@doc` string highlighting rules because there are too many cases where they don't work too well. I also want to get this out as soon as possible. I spent enough time working on this and also polishing it. Anything else can be added or reworked at a later time. :+1:

**Comment by azizk** [comment]
Good news! It's finally ready. :relieved: :tada: :partying_face: :tada:

**Comment by princemaple** [comment]
Great!! I'll do a quick test today and merge. Thanks for the hard work @azizk !

**Comment by princemaple** [comment]
There are a few color changes that I need to get used to, but it looks great overall. Thanks again for the great work.

**Comment by azizk** [comment]
Thanks! You're welcome! Yeah, that was quite the journey. It was also hard to stop myself from wanting to improve and polish things without end. Even if it's pretty shiny now, it's also good to release things once in a while. I think I've unintentionally become an expert in writing syntax files for Sublime Text. :grin:

Did you mean the color of `def`, `defmodule` and others? I think that change happened because of an ST4 update. I'm sure I also made some noticeable color changes but right now I only remember making attributes like `@some_attr` purple (in Monokai) to make them look like constants. I'm not the best with colors so it's possible someone with more skill could improve the overall look. :grinning:

**Comment by princemaple** [comment]
I meant the color of module names. I use ayu mirage and a lot of the names used to be blue and are now green-ish. It's fine, I can get used to them. If I can't, I can always just tweak the color scheme :) it's looking great overall.

**Pull request merged**
