### PR TITLE
Releasing v2.1.0

### PR DESCRIPTION
**Pull request by azizk**
This one took some doing :sweat_smile:

While you're at it, could you please capitalize "Sublime" in the about-text. Would look much better. Thanks! :+1:

### CODE REVIEW

**Comment by princemaple** [comment]
> could you please capitalize "Sublime" in the about-text.

Yup done!

**Comment by princemaple** [comment]
Are `~j` and `~y` from some packages or did you just declare some dummy sigils?

**Comment by azizk** [comment]
Well, they're defined in `Jason` and `YamlElixir`respectively. :)

**Comment by princemaple** [comment]
Thanks. Never knew that `Jason` came with a sigil.

**Comment by azizk** [comment]
I made a PR for that almost a year ago. :wink: :smile:

**Comment by princemaple** [comment]
Looks like it's not released yet. Hopefully soon.

**Comment by princemaple** [comment]
I added links to the two libs.

**Comment by azizk** [comment]
Oh wow, you're right. That's a bummer! All this time I thought it was already in the wild. :cry:

**Pull request merged**
